---
- name: Include system specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install the development tools
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ devtools }}"
  tags:
    - devtools
    - install
